name: D1 Admin SQL
on:
  workflow_dispatch:
    inputs:
      sql:
        description: SQL command to execute
        required: true
jobs:
  d1-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Run D1 SQL
        run: |
          npm install -g wrangler@3 --silent
          wrangler d1 execute cloud-mail-db --remote --command "${{ github.event.inputs.sql }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
